# Generated by Django 4.1.6 on 2023-07-03 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('college_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('dean', models.CharField(max_length=50)),
                ('college_office', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('name', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('office', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
