# Generated by Django 4.1.6 on 2023-07-03 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculty_app', '0001_initial'),
        ('college_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='chairs',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chairs', to='faculty_app.faculty'),
        ),
        migrations.AddField(
            model_name='department',
            name='college',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='college_app.college'),
        ),
    ]
