# Generated by Django 4.1.6 on 2023-07-03 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('college_app', '0002_initial'),
        ('faculty_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_number', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=50)),
                ('course_desc', models.TextField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='college_app.department')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('number', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('qtr', models.CharField(choices=[('Fall', 'Fall'), ('Winter', 'Winter'), ('Spring', 'Spring'), ('Summer', 'Summer')], max_length=15)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='course_app.course')),
                ('instructor_researcher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teach', to='faculty_app.instructor_researcher')),
            ],
        ),
    ]
