# Generated by Django 4.1.6 on 2023-06-28 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('number', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('qtr', models.CharField(choices=[('Fall', 'Fall'), ('Winter', 'Winter'), ('Spring', 'Spring'), ('Summer', 'Summer')], max_length=15)),
            ],
        ),
    ]
