# Generated by Django 4.1.6 on 2023-06-28 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='person_app.person')),
                ('rank', models.IntegerField()),
                ('f_office', models.IntegerField()),
                ('f_phone', models.CharField(max_length=15)),
                ('salary', models.PositiveIntegerField()),
            ],
            bases=('person_app.person',),
        ),
        migrations.CreateModel(
            name='Instructor_Researcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructor_of', to='faculty_app.faculty')),
            ],
        ),
    ]
