# Generated by Django 4.1.6 on 2023-07-03 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('college_app', '0001_initial'),
        ('person_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='person_app.person')),
                ('rank', models.IntegerField()),
                ('f_office', models.IntegerField()),
                ('f_phone', models.CharField(max_length=15)),
                ('salary', models.PositiveIntegerField()),
                ('departments', models.ManyToManyField(related_name='facul', to='college_app.department')),
            ],
            bases=('person_app.person',),
        ),
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('agency', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pl', to='faculty_app.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Instructor_Researcher',
            fields=[
                ('instructor_type', models.CharField(max_length=50)),
                ('instructor_ssn', models.CharField(max_length=15, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('time', models.IntegerField()),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supports', to='faculty_app.grant')),
                ('instructor_researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty_app.instructor_researcher')),
            ],
        ),
    ]
