# Generated by Django 4.1.6 on 2023-06-28 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student_app', '0001_initial'),
        ('faculty_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor_researcher',
            name='grade_student',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructor_researcher', to='student_app.grade_student'),
        ),
    ]
